name: axis_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pip
  # PyTorch & CUDA via Conda
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  # REMOVED tensorflow and protobuf from here to avoid conflicts
  - pip:
      - tensorflow # Moved to pip to ensure correct protobuf dependency
      - tensorflow-datasets
      - tensorflow-io
      - matplotlib
      - pandas
      - apache_beam
      - scipy
      - pytest
      - flake8
      - pyyaml
      - pillow