name: axis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pip
  # Install heavy ML frameworks via Conda (faster resolution & downloads)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tensorflow
  - tqdm
  - protobuf>=4.25.3 # Force newer protobuf for TF compatibility
  - pip:
      - tensorflow-datasets
      - tensorflow-io
      - matplotlib
      - pandas
      - apache_beam
